-- MySQL Script generated by MySQL Workbench
-- Wed Oct 25 18:40:39 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema FashionDesignDB
-- -----------------------------------------------------
DROP DATABASE IF EXISTS FashionDesignDB; 

CREATE DATABASE IF NOT EXISTS FashionDesignDB; 

USE FashionDesignDB;
-- -----------------------------------------------------
-- Table `User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `User` ;

CREATE TABLE IF NOT EXISTS `User` (
  `user_id` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`account_id`),
  INDEX `fk_Account_User_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_Account_User`
    FOREIGN KEY (`user_id`)
    REFERENCES `User` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Fashion Genre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Fashion Genre` ;

CREATE TABLE IF NOT EXISTS `Fashion Genre` (
  `genre_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`),
  UNIQUE INDEX `genre_name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Language` ;

CREATE TABLE IF NOT EXISTS `Language` (
  `language_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `dialect` VARCHAR(45) NULL,
  PRIMARY KEY (`language_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Region` ;

CREATE TABLE IF NOT EXISTS `Region` (
  `region_id` INT NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`region_id`),
  UNIQUE INDEX `country_UNIQUE` (`country` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model` ;

CREATE TABLE IF NOT EXISTS `Model` (
  `model_id` INT NOT NULL,
  `height` INT UNSIGNED NOT NULL,
  `weight` INT UNSIGNED NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `full_name` VARCHAR(100) NOT NULL,
  `biography` VARCHAR(100) NULL,
  `account_id` INT NOT NULL,
  `fashiongenre_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`model_id`, `team_id`),
  INDEX `fk_Model_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Model_Fashion Genre1_idx` (`fashiongenre_id` ASC) VISIBLE,
  INDEX `fk_Model_Language1_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_Model_Region1_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_Model_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model_Fashion Genre1`
    FOREIGN KEY (`fashiongenre_id`)
    REFERENCES `Fashion Genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model_Language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `Language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model_Region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Company` ;

CREATE TABLE IF NOT EXISTS `Company` (
  `company_id` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `employee_count` INT NOT NULL,
  `team_count` INT NOT NULL,
  `project_count` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Team`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Team` ;

CREATE TABLE IF NOT EXISTS `Team` (
  `team_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `employee_count` INT NOT NULL,
  `project_count` INT NOT NULL,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`team_id`),
  INDEX `fk_Team_Company1_idx` (`company_id` ASC) VISIBLE,
  CONSTRAINT `fk_Team_Company1`
    FOREIGN KEY (`company_id`)
    REFERENCES `Company` (`company_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Employer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Employer` ;

CREATE TABLE IF NOT EXISTS `Employer` (
  `employer_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(20) NOT NULL,
  `biography` VARCHAR(100) NULL,
  `account_id` INT NOT NULL,
  `fashiongenre_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`employer_id`),
  INDEX `fk_Employer_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Employer_Fashion Genre1_idx` (`fashiongenre_id` ASC) VISIBLE,
  INDEX `fk_Employer_Language1_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_Employer_Region1_idx` (`region_id` ASC) VISIBLE,
  INDEX `fk_Employer_Team1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Employer_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employer_Fashion Genre1`
    FOREIGN KEY (`fashiongenre_id`)
    REFERENCES `Fashion Genre` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employer_Language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `Language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employer_Region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Employer_Team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `Team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Registered Viewer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Registered Viewer` ;

CREATE TABLE IF NOT EXISTS `Registered Viewer` (
  `viewer_id` INT NOT NULL,
  `full_name` VARCHAR(45) NOT NULL,
  `biography` VARCHAR(100) NULL,
  `gender` VARCHAR(20) NOT NULL,
  `username` VARCHAR(100) NOT NULL,
  `account_id` INT NOT NULL,
  `language_id` INT NOT NULL,
  `region_id` INT NOT NULL,
  PRIMARY KEY (`viewer_id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  INDEX `fk_Registered Viewer_Account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_Registered Viewer_Language1_idx` (`language_id` ASC) VISIBLE,
  INDEX `fk_Registered Viewer_Region1_idx` (`region_id` ASC) VISIBLE,
  CONSTRAINT `fk_Registered Viewer_Account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered Viewer_Language1`
    FOREIGN KEY (`language_id`)
    REFERENCES `Language` (`language_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Registered Viewer_Region1`
    FOREIGN KEY (`region_id`)
    REFERENCES `Region` (`region_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Project` ;

CREATE TABLE IF NOT EXISTS `Project` (
  `project_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NULL,
  `employee_count` INT NOT NULL,
  `team_id` INT NOT NULL,
  PRIMARY KEY (`project_id`),
  INDEX `fk_Project_Team1_idx` (`team_id` ASC) VISIBLE,
  CONSTRAINT `fk_Project_Team1`
    FOREIGN KEY (`team_id`)
    REFERENCES `Team` (`team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Model Inquirys`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Model Inquirys` ;

CREATE TABLE IF NOT EXISTS `Model Inquirys` (
  `inquiry_id` INT NOT NULL,
  `model_id` INT NOT NULL,
  `Model_team_id` INT NOT NULL,
  `employer_id` INT NOT NULL,
  PRIMARY KEY (`inquiry_id`),
  INDEX `fk_Model Inquirys_Model1_idx` (`model_id` ASC, `Model_team_id` ASC) VISIBLE,
  INDEX `fk_Model Inquirys_Employer1_idx` (`employer_id` ASC) VISIBLE,
  CONSTRAINT `fk_Model Inquirys_Model1`
    FOREIGN KEY (`model_id` , `Model_team_id`)
    REFERENCES `Model` (`model_id` , `team_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Model Inquirys_Employer1`
    FOREIGN KEY (`employer_id`)
    REFERENCES `Employer` (`employer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payment Information`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Payment Information` ;

CREATE TABLE IF NOT EXISTS `Payment Information` (
  `payment_id` INT NOT NULL,
  `cardholder_name` VARCHAR(100) NOT NULL,
  `card_number` VARCHAR(45) NOT NULL,
  `billing_address` VARCHAR(45) NOT NULL,
  `modelinquiry_id` INT NOT NULL,
  PRIMARY KEY (`payment_id`),
  UNIQUE INDEX `card_number_UNIQUE` (`card_number` ASC) VISIBLE,
  INDEX `fk_Payment Information_Model Inquirys1_idx` (`modelinquiry_id` ASC) VISIBLE,
  CONSTRAINT `fk_Payment Information_Model Inquirys1`
    FOREIGN KEY (`modelinquiry_id`)
    REFERENCES `Model Inquirys` (`inquiry_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
